networks:
  net_1:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - net_1
  
  backend:
    build:
      context: ./backend
    networks:
      - net_1

  frontend:
    build:
      context: ./frontend
    networks:
      - net_1
